name: 'Dynamic Dot Env Action'
description: 'Build a .env file from Github secrets and from a file.'
author: 'Tyler Wright'
inputs:
  repo_owner:
    required: true
    description: 'Owner of the repository'
  repo_name:
    required: true
    description: 'Name of the repository'
  environment: 
    required: true
    description: 'This is the name of the environment you store your secrets'
    default: ''
  github_token:
    required: true
    description: 'A Personal Access Token with permissions to your repository secrets'
  append_file:
    required: false
    description: 'File to use to append to the .env file'
  pre_wrapper:
    required: false
    description: 'Only used for internal testing. Setting this will change the pre wrapper used'
    default: '${{'
  post_wrapper:
    required: false
    description: 'Only used for internal testing. Setting this will change the post wrapper used'
    default: '}}'
outputs:
  dynamic_dot_env_data:
    description: 'The raw env file data'
runs:
  using: 'node12'
  main: 'dist/index.js'