name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build-env-file:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          path: './dynamic-dot-env-action'

      - name: Generate Env Data
        id: dot_env_data
        uses: ./
        with:
          github_token: ${{ secrets.TEST_TOKEN }}
          environment: dev
          repo_owner: 'tylerxwright'
          repo_name: 'dynamic-dot-env-action'
          pre_wrapper: '$[['
          post_wrapper: ']]'
          secret_prefix: 'ENV_'
      
      - name: Output Env File
        env:
          ENV_FILE_DATA: ${{ steps.dot_env_data.outputs.dynamic_dot_env_data }}
        shell: bash
        run: 'echo "$ENV_FILE_DATA" > .env'
        
      - name: View Env File
        shell: bash
        run: 'cat ./.env'


