name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build-env-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'dynamic-dot-env-action'

      - uses: ./
        with:
          environment: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_owner: 'tylerxwright'
          repo_name: 'dynamic-dot-env-action'


